const fs = require("fs");
const path = require("path");
const bcrypt = require("bcryptjs");

const DB_DIR = path.join(__dirname, "..", "data");
const DB_FILE = path.join(DB_DIR, "applyswipe.json");

if (!fs.existsSync(DB_DIR)) {
  fs.mkdirSync(DB_DIR, { recursive: true });
}

async function seed() {
  console.log("🌱 Seeding ApplySwipe database...");

  const salt = await bcrypt.genSalt(10);
  const alexPasswordHash = await bcrypt.hash("password123", salt);
  const adminPasswordHash = await bcrypt.hash("admin123", salt);

  const now = new Date().toISOString();
  const weekAgo = new Date(Date.now() - 7 * 86400000).toISOString();
  const twoWeeksAgo = new Date(Date.now() - 14 * 86400000).toISOString();
  const threeDaysAgo = new Date(Date.now() - 3 * 86400000).toISOString();

  const alexUserId = "usr-alex-chen-001";
  const adminUserId = "usr-admin-system-001";
  const alexProfileId = "prf-alex-chen-001";

  const users = [
    {
      id: alexUserId,
      email: "alex@applyswipe.io",
      passwordHash: alexPasswordHash,
      name: "Alex Chen",
      role: "USER",
      isVerified: true,
      emailVerifiedAt: twoWeeksAgo,
      createdAt: twoWeeksAgo,
      updatedAt: now,
    },
    {
      id: adminUserId,
      email: "admin@applyswipe.io",
      passwordHash: adminPasswordHash,
      name: "System Administrator",
      role: "ADMIN",
      isVerified: true,
      emailVerifiedAt: twoWeeksAgo,
      createdAt: twoWeeksAgo,
      updatedAt: now,
    },
  ];

  const profiles = [
    {
      id: alexProfileId,
      userId: alexUserId,
      headline: "Senior Full Stack & AI Systems Engineer",
      bio: "Passionate engineer with 6+ years building resilient web applications, distributed microservices, and AI-driven workflow automations using React, Next.js, Node.js, and Python.",
      phone: "+1 (555) 234-5678",
      country: "United States",
      city: "San Francisco, CA",
      targetRoles: ["Senior Full Stack Engineer", "Staff Frontend Engineer", "AI Application Engineer"],
      experienceLevel: "Senior (6+ years)",
      preferredIndustries: ["Developer Tools", "AI / Machine Learning", "Fintech", "SaaS"],
      preferredEmploymentTypes: ["Full-time", "Contract"],
      remotePreference: "Remote",
      minSalary: 160000,
      salaryCurrency: "USD",
      onboardingCompleted: true,
      createdAt: twoWeeksAgo,
      updatedAt: now,
    },
  ];

  const skills = [
    { id: "skl-01", profileId: alexProfileId, name: "React", category: "Frontend", yearsExperience: 6, level: "EXPERT", createdAt: twoWeeksAgo, updatedAt: now },
    { id: "skl-02", profileId: alexProfileId, name: "Next.js", category: "Frontend", yearsExperience: 5, level: "EXPERT", createdAt: twoWeeksAgo, updatedAt: now },
    { id: "skl-03", profileId: alexProfileId, name: "TypeScript", category: "Languages", yearsExperience: 6, level: "EXPERT", createdAt: twoWeeksAgo, updatedAt: now },
    { id: "skl-04", profileId: alexProfileId, name: "Node.js", category: "Backend", yearsExperience: 6, level: "ADVANCED", createdAt: twoWeeksAgo, updatedAt: now },
    { id: "skl-05", profileId: alexProfileId, name: "Python", category: "Backend / AI", yearsExperience: 4, level: "ADVANCED", createdAt: twoWeeksAgo, updatedAt: now },
    { id: "skl-06", profileId: alexProfileId, name: "PostgreSQL", category: "Database", yearsExperience: 5, level: "ADVANCED", createdAt: twoWeeksAgo, updatedAt: now },
    { id: "skl-07", profileId: alexProfileId, name: "Tailwind CSS", category: "Frontend", yearsExperience: 4, level: "EXPERT", createdAt: twoWeeksAgo, updatedAt: now },
    { id: "skl-08", profileId: alexProfileId, name: "Docker", category: "DevOps", yearsExperience: 4, level: "INTERMEDIATE", createdAt: twoWeeksAgo, updatedAt: now },
    { id: "skl-09", profileId: alexProfileId, name: "FastAPI", category: "Backend", yearsExperience: 3, level: "ADVANCED", createdAt: twoWeeksAgo, updatedAt: now },
    { id: "skl-10", profileId: alexProfileId, name: "AWS", category: "Cloud", yearsExperience: 4, level: "INTERMEDIATE", createdAt: twoWeeksAgo, updatedAt: now },
    { id: "skl-11", profileId: alexProfileId, name: "GraphQL", category: "API", yearsExperience: 4, level: "ADVANCED", createdAt: twoWeeksAgo, updatedAt: now },
    { id: "skl-12", profileId: alexProfileId, name: "LangChain", category: "AI / LLM", yearsExperience: 2, level: "ADVANCED", createdAt: twoWeeksAgo, updatedAt: now },
  ];

  const experiences = [
    {
      id: "exp-01",
      profileId: alexProfileId,
      company: "TechVanguard Inc.",
      role: "Senior Full Stack Engineer",
      location: "San Francisco, CA (Remote)",
      isCurrent: true,
      startDate: "2022-03-01T00:00:00.000Z",
      endDate: null,
      description: "Spearheaded core web architecture for customer-facing SaaS product serving 250,000 monthly active users.",
      achievements: [
        "Architected Next.js App Router migration reducing LCP load times by 42%",
        "Designed and implemented high-throughput REST & GraphQL microservices handling 12,000 req/sec",
        "Integrated OpenAI function calling to automate 35% of manual support triage workflows",
        "Mentored a distributed team of 5 junior and mid-level software engineers"
      ],
      technologies: ["React", "Next.js", "TypeScript", "Node.js", "PostgreSQL", "Tailwind CSS", "Docker", "AWS"],
      createdAt: twoWeeksAgo,
      updatedAt: now,
    },
    {
      id: "exp-02",
      profileId: alexProfileId,
      company: "NextGen Labs",
      role: "Full Stack Software Engineer",
      location: "San Jose, CA",
      isCurrent: false,
      startDate: "2019-06-01T00:00:00.000Z",
      endDate: "2022-02-28T00:00:00.000Z",
      description: "Built collaborative developer productivity tools and scalable real-time dashboards.",
      achievements: [
        "Implemented real-time WebSocket state synchronization supporting 5,000 concurrent canvas editors",
        "Built automated CI/CD pipeline using GitHub Actions and Docker reducing deployment time from 40m to 8m",
        "Created custom UI component library adopting accessible WAI-ARIA standards"
      ],
      technologies: ["TypeScript", "React", "Node.js", "Redis", "PostgreSQL", "Docker", "Jest"],
      createdAt: twoWeeksAgo,
      updatedAt: now,
    },
  ];

  const educations = [
    {
      id: "edu-01",
      profileId: alexProfileId,
      institution: "University of California, Berkeley",
      degree: "Bachelor of Science",
      field: "Computer Science",
      startYear: 2015,
      endYear: 2019,
      gpa: "3.85",
      createdAt: twoWeeksAgo,
      updatedAt: now,
    },
  ];

  const projects = [
    {
      id: "prj-01",
      profileId: alexProfileId,
      name: "JobPulse",
      description: "Autonomous real-time developer job market analytics scraper and visualization platform.",
      technologies: ["Next.js", "TypeScript", "Python", "FastAPI", "PostgreSQL", "Tailwind CSS"],
      url: "https://jobpulse-demo.dev",
      githubUrl: "https://github.com/alexchen/jobpulse",
      highlights: [
        "Scrapes and indexes over 50,000 tech postings daily with automated deduplication",
        "Built responsive interactive charts using Recharts and Tailwind CSS"
      ],
      createdAt: twoWeeksAgo,
      updatedAt: now,
    },
    {
      id: "prj-02",
      profileId: alexProfileId,
      name: "PromptCraft Engine",
      description: "Developer testing playground for comparing LLM prompts, token consumption, and latency across providers.",
      technologies: ["React", "Node.js", "LangChain", "OpenAI API", "Tailwind CSS"],
      url: "https://promptcraft.dev",
      githubUrl: "https://github.com/alexchen/promptcraft",
      highlights: [
        "Supports side-by-side evaluation of Claude, GPT-4, and Gemini with cost breakdowns",
        "Earned 1,200+ GitHub stars from the open-source community"
      ],
      createdAt: twoWeeksAgo,
      updatedAt: now,
    },
  ];

  const certifications = [
    {
      id: "crt-01",
      profileId: alexProfileId,
      name: "AWS Certified Solutions Architect – Associate",
      issuer: "Amazon Web Services",
      issueDate: "2023-05-15T00:00:00.000Z",
      expiryDate: "2026-05-15T00:00:00.000Z",
      credentialId: "AWS-SAA-84920412",
      credentialUrl: "https://aws.amazon.com/verification",
      createdAt: twoWeeksAgo,
      updatedAt: now,
    },
  ];

  const alexResumeId = "res-alex-chen-master";
  const resumes = [
    {
      id: alexResumeId,
      userId: alexUserId,
      name: "Master Full Stack & AI Resume",
      fileUrl: "/uploads/resumes/alex-chen-master.pdf",
      rawText: "ALEX CHEN\nSenior Full Stack & AI Systems Engineer\nSan Francisco, CA | alex@applyswipe.io | +1 (555) 234-5678\n\nSUMMARY\nPassionate engineer with 6+ years building resilient web applications, distributed microservices, and AI-driven workflow automations using React, Next.js, Node.js, and Python.\n\nEXPERIENCE\nTechVanguard Inc. - Senior Full Stack Engineer (2022 - Present)\n- Architected Next.js App Router migration reducing LCP load times by 42%\n- Designed and implemented high-throughput REST & GraphQL microservices handling 12,000 req/sec\n- Integrated OpenAI function calling to automate 35% of manual support triage workflows\n- Mentored a distributed team of 5 junior and mid-level software engineers\n\nNextGen Labs - Full Stack Software Engineer (2019 - 2022)\n- Implemented real-time WebSocket state synchronization supporting 5,000 concurrent canvas editors\n- Built automated CI/CD pipeline using GitHub Actions and Docker reducing deployment time from 40m to 8m\n- Created custom UI component library adopting accessible WAI-ARIA standards\n\nEDUCATION\nUniversity of California, Berkeley - B.S. in Computer Science (2015 - 2019, GPA 3.85)\n\nSKILLS\nReact, Next.js, TypeScript, Node.js, Python, PostgreSQL, Tailwind CSS, Docker, FastAPI, AWS, GraphQL, LangChain",
      parsedData: {
        candidateName: "Alex Chen",
        skills: ["React", "Next.js", "TypeScript", "Node.js", "Python", "PostgreSQL", "Tailwind CSS", "Docker", "FastAPI", "AWS"],
        yearsOfExperience: 6,
      },
      isDefault: true,
      createdAt: twoWeeksAgo,
      updatedAt: now,
    },
    {
      id: "res-alex-chen-backend",
      userId: alexUserId,
      name: "Backend & Systems Focused Resume",
      fileUrl: "/uploads/resumes/alex-chen-backend.pdf",
      rawText: "ALEX CHEN - Backend Systems Engineer\nSpecializing in high-throughput distributed microservices, PostgreSQL query optimization, and Node.js/Python architectures.",
      parsedData: {
        candidateName: "Alex Chen",
        skills: ["Node.js", "Python", "PostgreSQL", "Docker", "AWS", "FastAPI", "Redis"],
        yearsOfExperience: 6,
      },
      isDefault: false,
      createdAt: weekAgo,
      updatedAt: now,
    },
  ];

  const resumeVersions = [
    {
      id: "rv-alex-001",
      resumeId: alexResumeId,
      jobId: "job-linear-01",
      versionType: "TAILORED",
      title: "Senior Full Stack Engineer - Linear Tailored",
      targetRole: "Senior Full Stack Engineer",
      summary: "Senior Full Stack Engineer with 6+ years specializing in high-performance React, TypeScript, and modern UI architectures. Proven record reducing web vitals by 42% and crafting polished, keyboard-driven SaaS workflows aligned with Linear's craftsmanship.",
      skills: ["React", "TypeScript", "Next.js", "Tailwind CSS", "Node.js", "PostgreSQL", "GraphQL", "Performance Optimization"],
      experienceHighlights: [
        "Architected Next.js App Router migration reducing LCP load times by 42% with obsessive focus on interaction latency",
        "Created custom high-performance keyboard navigation systems and responsive command palette components",
        "Engineered scalable REST and GraphQL APIs with PostgreSQL database layer"
      ],
      fullContent: "ALEX CHEN — TAILORED FOR LINEAR\nSenior Full Stack Engineer\n\nSUMMARY\nSenior Full Stack Engineer with 6+ years specializing in high-performance React, TypeScript, and modern UI architectures.\n\nTARGETED SKILLS\nReact • TypeScript • Next.js • Tailwind CSS • Node.js • PostgreSQL • GraphQL\n\nRELEVANT HIGHLIGHTS\n- Led Next.js App Router migration achieving sub-100ms render response times\n- Engineered real-time collaborative state synchronization engines\n- Crafted keyboard-first accessible design components with zero jank",
      matchScore: 94,
      createdAt: threeDaysAgo,
      updatedAt: now,
    },
  ];

  const jobs = [
    {
      id: "job-linear-01",
      externalId: "lin-eng-4091",
      source: "linear-ats",
      title: "Senior Full Stack Engineer",
      company: "Linear",
      companyLogo: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&h=128&fit=crop",
      description: "Linear is building the operating system for modern software development. We're looking for an exceptional Senior Full Stack Engineer who obsesses over product speed, keyboard ergonomics, and sublime user experience. You will work on our real-time synchronization engine, web client, and desktop application using React, TypeScript, Node.js, and GraphQL.",
      location: "San Francisco, CA / Remote",
      remote: true,
      employmentType: "Full-time",
      experienceLevel: "Senior",
      salaryMin: 165000,
      salaryMax: 215000,
      salaryCurrency: "USD",
      skills: ["React", "TypeScript", "Node.js", "GraphQL", "PostgreSQL", "Tailwind CSS"],
      applicationUrl: "https://linear.app/careers/senior-full-stack",
      applicationType: "API_SUPPORTED",
      atsProvider: "GREENHOUSE",
      isReported: false,
      isActive: true,
      postedAt: "2026-09-28T14:30:00.000Z",
      expiresAt: "2026-11-28T00:00:00.000Z",
      createdAt: "2026-09-28T14:30:00.000Z",
      updatedAt: now,
    },
    {
      id: "job-vercel-02",
      externalId: "vcl-arch-8812",
      source: "vercel-careers",
      title: "Staff Frontend Architect",
      company: "Vercel",
      companyLogo: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&h=128&fit=crop",
      description: "Join the team shaping the future of the Web. At Vercel, you will push the boundaries of Next.js, React Server Components, and Edge computing. We seek a Staff Frontend Architect who can design world-class developer experiences, optimize build pipelines, and drive framework innovations.",
      location: "Remote (Global)",
      remote: true,
      employmentType: "Full-time",
      experienceLevel: "Staff / Lead",
      salaryMin: 195000,
      salaryMax: 255000,
      salaryCurrency: "USD",
      skills: ["Next.js", "React", "TypeScript", "Web Performance", "Edge Computing", "Tailwind CSS"],
      applicationUrl: "https://vercel.com/careers/staff-frontend-architect",
      applicationType: "API_SUPPORTED",
      atsProvider: "LEVER",
      isReported: false,
      isActive: true,
      postedAt: "2026-09-29T10:00:00.000Z",
      expiresAt: "2026-12-01T00:00:00.000Z",
      createdAt: "2026-09-29T10:00:00.000Z",
      updatedAt: now,
    },
    {
      id: "job-stripe-03",
      externalId: "strp-plat-1029",
      source: "stripe-api",
      title: "Senior Platform & Infrastructure Engineer",
      company: "Stripe",
      companyLogo: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=128&h=128&fit=crop",
      description: "Stripe powers economic infrastructure for the internet. As a Senior Platform Engineer on our Developer Productivity group, you will build distributed orchestration tools, containerized build environments, and developer CLI tooling used by thousands of internal engineers.",
      location: "San Francisco, CA / Seattle, WA / Remote",
      remote: true,
      employmentType: "Full-time",
      experienceLevel: "Senior",
      salaryMin: 190000,
      salaryMax: 250000,
      salaryCurrency: "USD",
      skills: ["Node.js", "TypeScript", "Docker", "AWS", "PostgreSQL", "Go"],
      applicationUrl: "https://stripe.com/jobs/senior-platform-engineer",
      applicationType: "FORM_SUPPORTED",
      atsProvider: "GREENHOUSE",
      isReported: false,
      isActive: true,
      postedAt: "2026-09-27T16:00:00.000Z",
      expiresAt: "2026-11-20T00:00:00.000Z",
      createdAt: "2026-09-27T16:00:00.000Z",
      updatedAt: now,
    },
    {
      id: "job-acme-04",
      externalId: "acme-eng-552",
      source: "acme-public",
      title: "Senior Full Stack Product Engineer",
      company: "ACME Corp",
      companyLogo: "https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=128&h=128&fit=crop",
      description: "ACME is modernizing enterprise supply-chain intelligence. We are hiring a Senior Full Stack Engineer to lead greenfield product verticals. You will take ownership from database schemas up to responsive React interfaces with TypeScript, Next.js, and PostgreSQL.",
      location: "Remote (US / Canada)",
      remote: true,
      employmentType: "Full-time",
      experienceLevel: "Senior",
      salaryMin: 140000,
      salaryMax: 180000,
      salaryCurrency: "USD",
      skills: ["React", "TypeScript", "Node.js", "PostgreSQL", "Docker", "AWS"],
      applicationUrl: "https://acme.corp/careers/fullstack-eng",
      applicationType: "FORM_SUPPORTED",
      atsProvider: "LEVER",
      isReported: false,
      isActive: true,
      postedAt: "2026-09-30T09:15:00.000Z",
      expiresAt: "2026-11-30T00:00:00.000Z",
      createdAt: "2026-09-30T09:15:00.000Z",
      updatedAt: now,
    },
    {
      id: "job-supabase-05",
      externalId: "supa-be-394",
      source: "supabase-jobs",
      title: "Senior Backend Engineer (Postgres & Realtime)",
      company: "Supabase",
      companyLogo: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=128&h=128&fit=crop",
      description: "Supabase is the open source Firebase alternative. We're seeking an experienced Backend Engineer to scale our managed PostgreSQL and real-time streaming infrastructure. Deep SQL, WAL replication, and distributed systems background required.",
      location: "Remote (Global)",
      remote: true,
      employmentType: "Full-time",
      experienceLevel: "Senior",
      salaryMin: 155000,
      salaryMax: 200000,
      salaryCurrency: "USD",
      skills: ["PostgreSQL", "Node.js", "Docker", "TypeScript", "Go", "AWS"],
      applicationUrl: "https://supabase.com/careers/senior-backend-engineer",
      applicationType: "API_SUPPORTED",
      atsProvider: "GREENHOUSE",
      isReported: false,
      isActive: true,
      postedAt: "2026-09-25T11:00:00.000Z",
      expiresAt: "2026-11-15T00:00:00.000Z",
      createdAt: "2026-09-25T11:00:00.000Z",
      updatedAt: now,
    },
    {
      id: "job-datadog-06",
      externalId: "dd-eng-9011",
      source: "datadog-ats",
      title: "Senior Full Stack Engineer - Observability UI",
      company: "Datadog",
      companyLogo: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=128&h=128&fit=crop",
      description: "Datadog processes trillions of telemetry events per day. Join our Core Dashboards team to create intuitive, ultra-fast visualization interfaces for millions of cloud engineers.",
      location: "New York, NY / Remote",
      remote: true,
      employmentType: "Full-time",
      experienceLevel: "Senior",
      salaryMin: 170000,
      salaryMax: 220000,
      salaryCurrency: "USD",
      skills: ["React", "TypeScript", "Node.js", "Python", "Docker"],
      applicationUrl: "https://datadoghq.com/careers/fullstack-observability",
      applicationType: "MANUAL_REQUIRED",
      atsProvider: "WORKDAY",
      isReported: false,
      isActive: true,
      postedAt: "2026-09-26T15:00:00.000Z",
      expiresAt: "2026-11-25T00:00:00.000Z",
      createdAt: "2026-09-26T15:00:00.000Z",
      updatedAt: now,
    },
    {
      id: "job-retool-07",
      externalId: "ret-ai-104",
      source: "retool-careers",
      title: "Senior AI Application Engineer",
      company: "Retool",
      companyLogo: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&h=128&fit=crop",
      description: "Build the future of AI-augmented software development. At Retool, you will build AI agent workflows, vector embeddings search, and code generation primitives that let developers build internal apps 10x faster.",
      location: "San Francisco, CA / Remote",
      remote: true,
      employmentType: "Full-time",
      experienceLevel: "Senior",
      salaryMin: 175000,
      salaryMax: 225000,
      salaryCurrency: "USD",
      skills: ["TypeScript", "Python", "LangChain", "React", "PostgreSQL", "FastAPI"],
      applicationUrl: "https://retool.com/careers/senior-ai-engineer",
      applicationType: "API_SUPPORTED",
      atsProvider: "GREENHOUSE",
      isReported: false,
      isActive: true,
      postedAt: "2026-09-28T18:00:00.000Z",
      expiresAt: "2026-12-05T00:00:00.000Z",
      createdAt: "2026-09-28T18:00:00.000Z",
      updatedAt: now,
    },
    {
      id: "job-figma-08",
      externalId: "fig-web-771",
      source: "figma-jobs",
      title: "Senior Web Systems Engineer",
      company: "Figma",
      companyLogo: "https://images.unsplash.com/photo-1542744094-3a31727560fa?w=128&h=128&fit=crop",
      description: "Help make design accessible to all. We are hiring a Senior Web Engineer to optimize our web app performance, collaboration infrastructure, and real-time asset pipelines.",
      location: "San Francisco, CA / Remote",
      remote: true,
      employmentType: "Full-time",
      experienceLevel: "Senior",
      salaryMin: 165000,
      salaryMax: 215000,
      salaryCurrency: "USD",
      skills: ["React", "TypeScript", "Node.js", "Web Performance", "Tailwind CSS"],
      applicationUrl: "https://figma.com/careers/senior-web-systems",
      applicationType: "FORM_SUPPORTED",
      atsProvider: "LEVER",
      isReported: false,
      isActive: true,
      postedAt: "2026-09-24T13:20:00.000Z",
      expiresAt: "2026-11-18T00:00:00.000Z",
      createdAt: "2026-09-24T13:20:00.000Z",
      updatedAt: now,
    },
    {
      id: "job-resend-09",
      externalId: "rsd-lead-302",
      source: "resend-jobs",
      title: "Lead TypeScript & Developer Experience Engineer",
      company: "Resend",
      companyLogo: "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=128&h=128&fit=crop",
      description: "Resend is the email platform for developers. We are seeking a Lead TypeScript Engineer to build SDKs, Next.js email templates, and high-reliability delivery webhooks.",
      location: "Remote (Global)",
      remote: true,
      employmentType: "Full-time",
      experienceLevel: "Lead",
      salaryMin: 160000,
      salaryMax: 210000,
      salaryCurrency: "USD",
      skills: ["TypeScript", "Next.js", "React", "Node.js", "REST APIs"],
      applicationUrl: "https://resend.com/careers/lead-typescript-engineer",
      applicationType: "API_SUPPORTED",
      atsProvider: "GREENHOUSE",
      isReported: false,
      isActive: true,
      postedAt: "2026-09-29T12:00:00.000Z",
      expiresAt: "2026-11-29T00:00:00.000Z",
      createdAt: "2026-09-29T12:00:00.000Z",
      updatedAt: now,
    },
    {
      id: "job-github-10",
      externalId: "gh-ux-8041",
      source: "github-careers",
      title: "Principal Design Technologist / UX Engineer",
      company: "GitHub",
      companyLogo: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&h=128&fit=crop",
      description: "Shape the developer experience for 100+ million software creators. You will partner with design and engineering teams to prototype and build high-fidelity Primer component systems.",
      location: "Remote (US)",
      remote: true,
      employmentType: "Full-time",
      experienceLevel: "Principal",
      salaryMin: 185000,
      salaryMax: 240000,
      salaryCurrency: "USD",
      skills: ["React", "TypeScript", "Tailwind CSS", "Accessibility", "Design Systems"],
      applicationUrl: "https://github.com/careers/principal-ux-engineer",
      applicationType: "MANUAL_REQUIRED",
      atsProvider: "WORKDAY",
      isReported: false,
      isActive: true,
      postedAt: "2026-09-27T08:00:00.000Z",
      expiresAt: "2026-11-20T00:00:00.000Z",
      createdAt: "2026-09-27T08:00:00.000Z",
      updatedAt: now,
    },
    {
      id: "job-hashicorp-11",
      externalId: "hashi-cld-210",
      source: "hashicorp-jobs",
      title: "Senior Cloud Infrastructure Engineer",
      company: "HashiCorp",
      companyLogo: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=128&h=128&fit=crop",
      description: "Scale Terraform Cloud and Nomad managed services across multi-region AWS and Kubernetes clusters.",
      location: "Austin, TX / Remote",
      remote: true,
      employmentType: "Full-time",
      experienceLevel: "Senior",
      salaryMin: 155000,
      salaryMax: 200000,
      salaryCurrency: "USD",
      skills: ["Docker", "AWS", "Go", "Kubernetes", "PostgreSQL"],
      applicationUrl: "https://hashicorp.com/careers/cloud-infra-engineer",
      applicationType: "FORM_SUPPORTED",
      atsProvider: "GREENHOUSE",
      isReported: false,
      isActive: true,
      postedAt: "2026-09-23T14:00:00.000Z",
      expiresAt: "2026-11-10T00:00:00.000Z",
      createdAt: "2026-09-23T14:00:00.000Z",
      updatedAt: now,
    },
    {
      id: "job-anthropic-12",
      externalId: "anth-sys-992",
      source: "anthropic-careers",
      title: "AI Systems Full Stack Engineer",
      company: "Anthropic",
      companyLogo: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&h=128&fit=crop",
      description: "Build state-of-the-art interactive interfaces and evaluation pipelines for Claude. Work at the bleeding edge of AI safety, multi-turn reasoning, and multimodal inputs.",
      location: "San Francisco, CA (Hybrid)",
      remote: false,
      employmentType: "Full-time",
      experienceLevel: "Senior",
      salaryMin: 220000,
      salaryMax: 290000,
      salaryCurrency: "USD",
      skills: ["Python", "TypeScript", "React", "FastAPI", "Docker", "LangChain"],
      applicationUrl: "https://anthropic.com/careers/ai-systems-engineer",
      applicationType: "FORM_SUPPORTED",
      atsProvider: "LEVER",
      isReported: false,
      isActive: true,
      postedAt: "2026-09-29T15:45:00.000Z",
      expiresAt: "2026-12-15T00:00:00.000Z",
      createdAt: "2026-09-29T15:45:00.000Z",
      updatedAt: now,
    },
    {
      id: "job-warp-13",
      externalId: "warp-eng-102",
      source: "warp-jobs",
      title: "Senior Full Stack Engineer - Warp Cloud",
      company: "Warp",
      companyLogo: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=128&h=128&fit=crop",
      description: "Warp is building the terminal for the 21st century. Join us to build collaborative cloud sessions, terminal AI workflows, and instant command-sharing features.",
      location: "New York, NY / Remote",
      remote: true,
      employmentType: "Full-time",
      experienceLevel: "Senior",
      salaryMin: 165000,
      salaryMax: 215000,
      salaryCurrency: "USD",
      skills: ["TypeScript", "React", "Rust", "Node.js", "GraphQL"],
      applicationUrl: "https://warp.dev/careers/senior-full-stack",
      applicationType: "API_SUPPORTED",
      atsProvider: "GREENHOUSE",
      isReported: false,
      isActive: true,
      postedAt: "2026-09-26T17:00:00.000Z",
      expiresAt: "2026-11-26T00:00:00.000Z",
      createdAt: "2026-09-26T17:00:00.000Z",
      updatedAt: now,
    },
    {
      id: "job-scaleai-14",
      externalId: "scale-be-401",
      source: "scale-careers",
      title: "Backend Engineer (Python & Data Systems)",
      company: "Scale AI",
      companyLogo: "https://images.unsplash.com/photo-1542744094-3a31727560fa?w=128&h=128&fit=crop",
      description: "Scale delivers high quality training data for enterprise AI models. You will architect high throughput ingestion pipelines handling petabytes of unstructured text, audio, and video.",
      location: "San Francisco, CA / Remote",
      remote: true,
      employmentType: "Full-time",
      experienceLevel: "Mid-Senior",
      salaryMin: 150000,
      salaryMax: 195000,
      salaryCurrency: "USD",
      skills: ["Python", "FastAPI", "PostgreSQL", "Docker", "AWS"],
      applicationUrl: "https://scale.com/careers/backend-data-engineer",
      applicationType: "FORM_SUPPORTED",
      atsProvider: "GREENHOUSE",
      isReported: false,
      isActive: true,
      postedAt: "2026-09-25T14:00:00.000Z",
      expiresAt: "2026-11-19T00:00:00.000Z",
      createdAt: "2026-09-25T14:00:00.000Z",
      updatedAt: now,
    },
    {
      id: "job-browserco-15",
      externalId: "arc-dsn-294",
      source: "browser-co",
      title: "Design Engineer (Arc Browser Web Platform)",
      company: "The Browser Company",
      companyLogo: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&h=128&fit=crop",
      description: "We are reimagining how we use the internet. Looking for a Design Engineer who moves fluidly between Figma and production React / TypeScript code.",
      location: "New York, NY / Remote",
      remote: true,
      employmentType: "Full-time",
      experienceLevel: "Senior",
      salaryMin: 160000,
      salaryMax: 210000,
      salaryCurrency: "USD",
      skills: ["React", "TypeScript", "Tailwind CSS", "Framer Motion", "UI Design"],
      applicationUrl: "https://thebrowser.company/careers/design-engineer",
      applicationType: "API_SUPPORTED",
      atsProvider: "LEVER",
      isReported: false,
      isActive: true,
      postedAt: "2026-09-28T12:00:00.000Z",
      expiresAt: "2026-11-28T00:00:00.000Z",
      createdAt: "2026-09-28T12:00:00.000Z",
      updatedAt: now,
    },
    {
      id: "job-discord-16",
      externalId: "disc-rn-883",
      source: "discord-ats",
      title: "Senior React Native Engineer",
      company: "Discord",
      companyLogo: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=128&h=128&fit=crop",
      description: "Discord is where 200 million people hang out. Help us build lightning-fast cross-platform features using React Native, TypeScript, and modern mobile ergonomics.",
      location: "San Francisco, CA / Remote",
      remote: true,
      employmentType: "Full-time",
      experienceLevel: "Senior",
      salaryMin: 165000,
      salaryMax: 215000,
      salaryCurrency: "USD",
      skills: ["React", "TypeScript", "React Native", "Mobile Performance", "Node.js"],
      applicationUrl: "https://discord.com/careers/senior-react-native",
      applicationType: "MANUAL_REQUIRED",
      atsProvider: "WORKDAY",
      isReported: false,
      isActive: true,
      postedAt: "2026-09-22T09:00:00.000Z",
      expiresAt: "2026-11-12T00:00:00.000Z",
      createdAt: "2026-09-22T09:00:00.000Z",
      updatedAt: now,
    },
    {
      id: "job-prisma-17",
      externalId: "prs-dev-110",
      source: "prisma-careers",
      title: "Developer Experience & Full Stack Engineer",
      company: "Prisma",
      companyLogo: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=128&h=128&fit=crop",
      description: "Build developer tools that make data easy. Create interactive playgrounds, data browser features, and benchmark developer experience workflows with TypeScript and Next.js.",
      location: "Remote (Global)",
      remote: true,
      employmentType: "Full-time",
      experienceLevel: "Mid-Senior",
      salaryMin: 130000,
      salaryMax: 175000,
      salaryCurrency: "USD",
      skills: ["TypeScript", "PostgreSQL", "Next.js", "Node.js", "Docker"],
      applicationUrl: "https://prisma.io/careers/developer-experience",
      applicationType: "API_SUPPORTED",
      atsProvider: "GREENHOUSE",
      isReported: false,
      isActive: true,
      postedAt: "2026-09-25T16:00:00.000Z",
      expiresAt: "2026-11-18T00:00:00.000Z",
      createdAt: "2026-09-25T16:00:00.000Z",
      updatedAt: now,
    },
    {
      id: "job-cloudflare-18",
      externalId: "cf-sec-712",
      source: "cloudflare-jobs",
      title: "Senior Security Software Engineer",
      company: "Cloudflare",
      companyLogo: "https://images.unsplash.com/photo-1557804506-669a67965ba0?w=128&h=128&fit=crop",
      description: "Help build a better, safer Internet. Work on edge zero-trust policies, distributed DDoS mitigation systems, and cryptographic certificate distribution.",
      location: "Austin, TX / San Francisco / Remote",
      remote: true,
      employmentType: "Full-time",
      experienceLevel: "Senior",
      salaryMin: 170000,
      salaryMax: 220000,
      salaryCurrency: "USD",
      skills: ["Go", "Node.js", "Docker", "AWS", "Security"],
      applicationUrl: "https://cloudflare.com/careers/senior-security-engineer",
      applicationType: "MANUAL_REQUIRED",
      atsProvider: "GREENHOUSE",
      isReported: false,
      isActive: true,
      postedAt: "2026-09-27T10:00:00.000Z",
      expiresAt: "2026-11-20T00:00:00.000Z",
      createdAt: "2026-09-27T10:00:00.000Z",
      updatedAt: now,
    },
    {
      id: "job-snowflake-19",
      externalId: "snow-dt-501",
      source: "snowflake-careers",
      title: "Senior Cloud Data Infrastructure Engineer",
      company: "Snowflake",
      companyLogo: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=128&h=128&fit=crop",
      description: "Scale the Data Cloud. Help architect multi-cloud query execution runtimes, cross-region replication services, and high-throughput telemetry pipelines.",
      location: "San Mateo, CA / Remote",
      remote: true,
      employmentType: "Full-time",
      experienceLevel: "Senior",
      salaryMin: 165000,
      salaryMax: 220000,
      salaryCurrency: "USD",
      skills: ["Python", "PostgreSQL", "AWS", "Docker", "Go"],
      applicationUrl: "https://snowflake.com/careers/data-infrastructure-engineer",
      applicationType: "FORM_SUPPORTED",
      atsProvider: "WORKDAY",
      isReported: false,
      isActive: true,
      postedAt: "2026-09-24T18:00:00.000Z",
      expiresAt: "2026-11-15T00:00:00.000Z",
      createdAt: "2026-09-24T18:00:00.000Z",
      updatedAt: now,
    },
    {
      id: "job-loom-20",
      externalId: "loom-gro-219",
      source: "loom-jobs",
      title: "Growth & Product Engineer",
      company: "Loom",
      companyLogo: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&h=128&fit=crop",
      description: "Loom makes asynchronous video communication intuitive. Build viral acquisition loops, seamless team onboarding, and AI transcript search experiences.",
      location: "Remote (US)",
      remote: true,
      employmentType: "Full-time",
      experienceLevel: "Mid-Senior",
      salaryMin: 140000,
      salaryMax: 180000,
      salaryCurrency: "USD",
      skills: ["React", "TypeScript", "Next.js", "Node.js", "PostgreSQL"],
      applicationUrl: "https://loom.com/careers/growth-product-engineer",
      applicationType: "API_SUPPORTED",
      atsProvider: "LEVER",
      isReported: false,
      isActive: true,
      postedAt: "2026-09-26T12:00:00.000Z",
      expiresAt: "2026-11-26T00:00:00.000Z",
      createdAt: "2026-09-26T12:00:00.000Z",
      updatedAt: now,
    },
  ];

  const jobSources = [
    {
      id: "src-01",
      name: "Greenhouse Direct ATS",
      type: "ATS",
      url: "https://boards-api.greenhouse.io",
      isActive: true,
      lastSyncAt: now,
      jobCount: 8,
      config: { apiVersion: "v1", rateLimitPerMinute: 60 },
      createdAt: twoWeeksAgo,
      updatedAt: now,
    },
    {
      id: "src-02",
      name: "Lever Postings API",
      type: "ATS",
      url: "https://api.lever.co/v0",
      isActive: true,
      lastSyncAt: now,
      jobCount: 6,
      config: { apiVersion: "v0" },
      createdAt: twoWeeksAgo,
      updatedAt: now,
    },
    {
      id: "src-03",
      name: "RemoteOK & Web3 Licensed Feeds",
      type: "FEED",
      url: "https://remoteok.com/api",
      isActive: true,
      lastSyncAt: now,
      jobCount: 6,
      config: { pollIntervalMinutes: 30 },
      createdAt: twoWeeksAgo,
      updatedAt: now,
    },
  ];

  const savedJobs = [
    {
      id: "sav-01",
      userId: alexUserId,
      jobId: "job-acme-04",
      notes: "Exciting greenfield architecture role with strong focus on Next.js.",
      createdAt: threeDaysAgo,
    },
    {
      id: "sav-02",
      userId: alexUserId,
      jobId: "job-figma-08",
      notes: "High caliber team; review design systems before interview.",
      createdAt: weekAgo,
    },
  ];

  const jobInteractions = [
    { id: "int-01", userId: alexUserId, jobId: "job-linear-01", interactionType: "APPLIED", metadata: { matchScore: 94 }, createdAt: threeDaysAgo },
    { id: "int-02", userId: alexUserId, jobId: "job-vercel-02", interactionType: "APPLIED", metadata: { matchScore: 91 }, createdAt: weekAgo },
    { id: "int-03", userId: alexUserId, jobId: "job-stripe-03", interactionType: "APPLIED", metadata: { matchScore: 86 }, createdAt: twoWeeksAgo },
    { id: "int-04", userId: alexUserId, jobId: "job-acme-04", interactionType: "SAVED", metadata: { matchScore: 92 }, createdAt: threeDaysAgo },
    { id: "int-05", userId: alexUserId, jobId: "job-datadog-06", interactionType: "PASSED", metadata: { reason: "Prefer 100% remote without travel" }, createdAt: weekAgo },
  ];

  const applications = [
    {
      id: "app-linear-01",
      userId: alexUserId,
      jobId: "job-linear-01",
      status: "INTERVIEW",
      mode: "SMART_APPLY",
      submissionCapability: "API_SUPPORTED",
      matchScore: 94,
      matchExplanation: "Exceptional alignment with Linear's frontend performance, React, TypeScript, and modern UX expectations.",
      submissionMethod: "API",
      externalApplicationId: "lin-app-84920",
      notes: "Technical screen scheduled with Engineering Director for next Tuesday at 2:00 PM PST.",
      submittedAt: threeDaysAgo,
      interviewDate: "2026-10-06T21:00:00.000Z",
      createdAt: threeDaysAgo,
      updatedAt: now,
    },
    {
      id: "app-vercel-02",
      userId: alexUserId,
      jobId: "job-vercel-02",
      status: "SUBMITTED",
      mode: "REVIEW_EVERYTHING",
      submissionCapability: "API_SUPPORTED",
      matchScore: 91,
      matchExplanation: "Strong match for Next.js App Router experience, React Server Components familiarity, and TypeScript mastery.",
      submissionMethod: "API",
      externalApplicationId: "vcl-app-2041",
      notes: "Application confirmed by Vercel Greenhouse portal.",
      submittedAt: weekAgo,
      interviewDate: null,
      createdAt: weekAgo,
      updatedAt: now,
    },
    {
      id: "app-stripe-03",
      userId: alexUserId,
      jobId: "job-stripe-03",
      status: "READY_FOR_REVIEW",
      mode: "REVIEW_EVERYTHING",
      submissionCapability: "FORM_SUPPORTED",
      matchScore: 86,
      matchExplanation: "Matches Docker, AWS, and TypeScript requirements. Candidate has strong distributed systems background.",
      submissionMethod: "FORM",
      externalApplicationId: null,
      notes: "AI prepared tailored resume and 4 answered questions. Ready for final review before submission.",
      submittedAt: null,
      interviewDate: null,
      createdAt: twoWeeksAgo,
      updatedAt: now,
    },
    {
      id: "app-retool-04",
      userId: alexUserId,
      jobId: "job-retool-07",
      status: "PREPARING",
      mode: "AUTOPILOT",
      submissionCapability: "API_SUPPORTED",
      matchScore: 89,
      matchExplanation: "Candidate possesses direct LangChain, Python, and TypeScript project experience (PromptCraft).",
      submissionMethod: "API",
      externalApplicationId: null,
      notes: "Autopilot is generating tailored resume and company-specific cover letter.",
      submittedAt: null,
      interviewDate: null,
      createdAt: now,
      updatedAt: now,
    },
  ];

  const applicationAnswers = [
    {
      id: "ans-01",
      applicationId: "app-linear-01",
      question: "Why do you want to work at Linear?",
      answer: "I am deeply obsessed with high-speed software ergonomics and craftsmanship. At TechVanguard, I led our Next.js App Router migration specifically to cut interaction latency by 42%. Linear sets the gold standard for how developer tools should feel, and I want to contribute to that speed and delight every single day.",
      isAiGenerated: true,
      isEdited: true,
      createdAt: threeDaysAgo,
      updatedAt: now,
    },
    {
      id: "ans-02",
      applicationId: "app-linear-01",
      question: "Describe a challenging performance issue you solved in React.",
      answer: "When building our real-time collaboration canvas at NextGen Labs, 5,000 concurrent state updates were causing frame drops. I re-architected the state tree to isolate canvas redraws using localized state slices and custom reconcilers, preserving 60 FPS under peak load.",
      isAiGenerated: true,
      isEdited: false,
      createdAt: threeDaysAgo,
      updatedAt: now,
    },
    {
      id: "ans-03",
      applicationId: "app-stripe-03",
      question: "What is your experience with container orchestration and Docker?",
      answer: "Over the past 4 years I have packaged microservices with multi-stage Docker builds and deployed them to AWS ECS. At NextGen Labs, I built a Dockerized CI pipeline that cut test and build turnaround from 40 to 8 minutes.",
      isAiGenerated: true,
      isEdited: false,
      createdAt: twoWeeksAgo,
      updatedAt: now,
    },
  ];

  const applicationDocuments = [
    {
      id: "doc-01",
      applicationId: "app-linear-01",
      type: "TAILORED_RESUME",
      title: "Alex Chen - Tailored Resume for Linear",
      content: "# ALEX CHEN\n**Senior Full Stack Engineer**\n*San Francisco, CA • alex@applyswipe.io*\n\n### PROFESSIONAL SUMMARY\nSenior Full Stack Engineer with 6+ years specializing in high-performance React, TypeScript, and modern UI architectures. Proven record reducing web vitals by 42% and crafting polished, keyboard-driven SaaS workflows aligned with Linear's craftsmanship.\n\n### CORE COMPETENCIES\nReact, TypeScript, Next.js, Tailwind CSS, Node.js, PostgreSQL, GraphQL, Performance Optimization\n\n### EXPERIENCE\n**TechVanguard Inc.** — *Senior Full Stack Engineer* (2022 – Present)\n- Architected Next.js App Router migration reducing LCP load times by 42% with obsessive focus on interaction latency\n- Created custom high-performance keyboard navigation systems and responsive command palette components\n- Engineered scalable REST and GraphQL APIs with PostgreSQL database layer\n\n**NextGen Labs** — *Full Stack Engineer* (2019 – 2022)\n- Implemented real-time WebSocket state synchronization supporting 5,000 concurrent canvas editors\n- Built automated CI/CD pipeline using GitHub Actions and Docker reducing deployment time from 40m to 8m",
      fileUrl: "/generated/alex-chen-linear.pdf",
      createdAt: threeDaysAgo,
      updatedAt: now,
    },
    {
      id: "doc-02",
      applicationId: "app-linear-01",
      type: "COVER_LETTER",
      title: "Cover Letter - Linear",
      content: "Dear Linear Engineering Team,\n\nI am writing to express my strong enthusiasm for the Senior Full Stack Engineer role at Linear. Having used Linear daily to manage software roadmaps, I have immense appreciation for your team's relentless dedication to sub-100ms response times, intuitive keyboard shortcuts, and refined typography.\n\nOver the past six years, I have specialized in building high-throughput web applications with React, Next.js, and TypeScript. In my current role at TechVanguard, I led our frontend performance re-architecture, cutting load times by 42% and building snappy UI micro-interactions that our users love. Previously at NextGen Labs, I built real-time WebSocket collaboration features supporting thousands of concurrent users.\n\nLinear represents the rare combination of top-tier engineering standards and obsessive product design. I would love the opportunity to contribute to Linear's next chapter.\n\nWarm regards,\nAlex Chen",
      fileUrl: null,
      createdAt: threeDaysAgo,
      updatedAt: now,
    },
  ];

  const applicationEvents = [
    { id: "evt-01", applicationId: "app-linear-01", eventType: "DISCOVERED", notes: "Job discovered via Linear ATS feed", createdAt: weekAgo },
    { id: "evt-02", applicationId: "app-linear-01", eventType: "VIEWED", notes: "User reviewed job match (94% AI Match)", createdAt: threeDaysAgo },
    { id: "evt-03", applicationId: "app-linear-01", eventType: "GENERATED_MATERIALS", notes: "AI tailored resume and generated customized cover letter", createdAt: threeDaysAgo },
    { id: "evt-04", applicationId: "app-linear-01", eventType: "SUBMITTED", notes: "Application submitted via Greenhouse Direct API with confirmation #lin-app-84920", createdAt: threeDaysAgo },
    { id: "evt-05", applicationId: "app-linear-01", eventType: "INTERVIEW_SCHEDULED", notes: "Recruiter invitation confirmed for Technical Round", createdAt: now },
  ];

  const userPreferences = [
    {
      id: "pref-alex-001",
      userId: alexUserId,
      targetRoles: ["Senior Full Stack Engineer", "Staff Frontend Engineer", "AI Application Engineer"],
      experienceLevel: "Senior",
      minSalary: 160000,
      salaryCurrency: "USD",
      remoteOnly: true,
      preferredLocations: ["United States", "Canada", "Remote"],
      employmentTypes: ["Full-time"],
      excludedCompanies: ["Legacy Enterprises Inc."],
      createdAt: twoWeeksAgo,
      updatedAt: now,
    },
  ];

  const autopilotSettings = [
    {
      id: "auto-alex-001",
      userId: alexUserId,
      isEnabled: true,
      minMatchScore: 85,
      dailyLimit: 10,
      applicationsToday: 3,
      allowedRoles: ["Full Stack Developer", "Senior Frontend Engineer", "AI Application Engineer"],
      allowedLocations: ["Remote", "San Francisco, CA"],
      minSalary: 160000,
      employmentTypes: ["Full-time"],
      excludedCompanies: ["Legacy Enterprises Inc."],
      mode: "SMART_APPLY",
      lastRunAt: threeDaysAgo,
      scannedCount: 42,
      matchedCount: 13,
      preparedCount: 9,
      submittedCount: 7,
      needsReviewCount: 2,
      createdAt: twoWeeksAgo,
      updatedAt: now,
    },
  ];

  const notifications = [
    {
      id: "notif-01",
      userId: alexUserId,
      title: "Interview Request Received! 🎉",
      message: "Linear has reviewed your application and scheduled a technical screen for next Tuesday.",
      type: "INTERVIEW",
      isRead: false,
      link: "/dashboard/applications/app-linear-01",
      createdAt: "2026-10-01T14:00:00.000Z",
    },
    {
      id: "notif-02",
      userId: alexUserId,
      title: "New High Match Job Discovered (94%)",
      message: "Senior Full Stack Engineer at Linear matches your target roles and React/TypeScript skills.",
      type: "JOB_MATCH",
      isRead: true,
      link: "/dashboard/discover",
      createdAt: threeDaysAgo,
    },
    {
      id: "notif-03",
      userId: alexUserId,
      title: "Application Needs Review",
      message: "Stripe Platform Engineer application has materials prepared and requires your confirmation.",
      type: "NEEDS_REVIEW",
      isRead: false,
      link: "/dashboard/applications/app-stripe-03",
      createdAt: twoWeeksAgo,
    },
  ];

  const subscriptions = [
    {
      id: "sub-alex-001",
      userId: alexUserId,
      plan: "PRO",
      status: "ACTIVE",
      currentPeriodStart: twoWeeksAgo,
      currentPeriodEnd: "2026-10-18T00:00:00.000Z",
      stripeCustomerId: "cus_applyswipe_alex_001",
      stripeSubscriptionId: "sub_applyswipe_alex_pro",
      createdAt: twoWeeksAgo,
      updatedAt: now,
    },
  ];

  const aiUsages = [
    {
      id: "ai-01",
      userId: alexUserId,
      operation: "RESUME_TAILORING",
      provider: "OPENAI",
      model: "gpt-4o",
      inputTokens: 1420,
      outputTokens: 680,
      estimatedCost: 0.0105,
      createdAt: threeDaysAgo,
    },
    {
      id: "ai-02",
      userId: alexUserId,
      operation: "COVER_LETTER",
      provider: "OPENAI",
      model: "gpt-4o",
      inputTokens: 1100,
      outputTokens: 420,
      estimatedCost: 0.0076,
      createdAt: threeDaysAgo,
    },
    {
      id: "ai-03",
      userId: alexUserId,
      operation: "MATCH_SCORING",
      provider: "LOCAL_ENGINE",
      model: "applyswipe-match-v1",
      inputTokens: 950,
      outputTokens: 250,
      estimatedCost: 0.0012,
      createdAt: now,
    },
  ];

  const databaseData = {
    users,
    profiles,
    skills,
    experiences,
    educations,
    projects,
    certifications,
    resumes,
    resumeVersions,
    jobs,
    jobSources,
    jobInteractions,
    savedJobs,
    applications,
    applicationAnswers,
    applicationDocuments,
    applicationEvents,
    userPreferences,
    autopilotSettings,
    notifications,
    subscriptions,
    payments: [],
    aiUsages,
    auditLogs: [],
  };

  fs.writeFileSync(DB_FILE, JSON.stringify(databaseData, null, 2), "utf-8");
  console.log(`✅ Successfully seeded database at ${DB_FILE}`);
  console.log(`- 20 Jobs across Linear, Vercel, Stripe, Acme, Retool, Supabase, etc.`);
  console.log(`- Demo user: alex@applyswipe.io (password: password123)`);
  console.log(`- Admin user: admin@applyswipe.io (password: admin123)`);
  console.log(`- Applications in Interview, Submitted, Ready for Review, and Preparing states.`);
}

seed().catch((err) => {
  console.error("❌ Seeding failed:", err);
  process.exit(1);
});
