import db from "@/lib/db";
import { ApplicationAgent, type AutomationResult } from "@/lib/applications/agent";
import { createLogger } from "@/lib/logger";
import type { Application, ApplicationStatus, Job, JobInteraction, SwipeAction } from "@/types";
import { resolveOfficialApplicationUrl, sourceLabelForProvider, toPublicJob } from "./job-service";

const log = createLogger("jobs:application");

/**
 * Application flow.
 *
 *   User clicks Apply -> create/update Application -> prepare tailored resume
 *   -> prepare cover letter -> show readiness -> open the OFFICIAL application
 *   URL -> the user applies on the employer site -> the user (or a verified ATS
 *   confirmation) marks the application as APPLIED.
 *
 * ApplySwipe never claims an application was submitted when it was not: the
 * only automatic submission path would require an ATS API that explicitly
 * supports it, which none of the configured providers expose.
 */

export const PREPARED_STATUSES: ApplicationStatus[] = [
  "SAVED",
  "PREPARING",
  "READY",
  "READY_FOR_REVIEW",
];

export const APPLIED_STATUSES: ApplicationStatus[] = ["SUBMITTED", "APPLIED", "INTERVIEW", "OFFER"];

const SWIPE_TO_INTERACTION: Record<SwipeAction, JobInteraction["interactionType"]> = {
  PASS: "PASSED",
  LIKE: "LIKE",
  SUPER_LIKE: "SUPER_LIKE",
};

export function isPrepared(status: string): boolean {
  return PREPARED_STATUSES.includes(status as ApplicationStatus);
}

/** APPLIED and SUBMITTED are the same thing semantically - the user applied. */
export function normalizeApplicationStatus(status: string): ApplicationStatus {
  if (status === "SUBMITTED") return "APPLIED";
  return status as ApplicationStatus;
}

export interface ApplicationReadiness {
  ready: boolean;
  missing: string[];
  tailoredResume: boolean;
  coverLetter: boolean;
  answeredQuestions: number;
  requiresExternalSubmission: boolean;
  canAutoSubmit: boolean;
  officialApplicationUrl: string | null;
  nextStep: string;
}

export interface PrepareApplicationResult {
  application: Application;
  readiness: ApplicationReadiness;
  agent: AutomationResult;
  job: ReturnType<typeof toPublicJob>;
  message: string;
}

function buildReadiness(
  application: Application,
  job: Job,
  documents: { type: string }[]
): ApplicationReadiness {
  const tailoredResume = documents.some((doc) => doc.type === "TAILORED_RESUME");
  const coverLetter = documents.some((doc) => doc.type === "COVER_LETTER");
  const answeredQuestions = (application as unknown as { answers?: unknown[] }).answers?.length || 0;

  const missing: string[] = [];
  if (!tailoredResume) missing.push("tailored_resume");
  if (!coverLetter) missing.push("cover_letter");

  const officialApplicationUrl = resolveOfficialApplicationUrl(job);
  if (!officialApplicationUrl) missing.push("application_url");

  const canAutoSubmit = false; // no configured provider exposes a reliable submission API

  return {
    ready: missing.length === 0,
    missing,
    tailoredResume,
    coverLetter,
    answeredQuestions,
    requiresExternalSubmission: true,
    canAutoSubmit,
    officialApplicationUrl,
    nextStep: officialApplicationUrl
      ? "Review your tailored materials, then open the employer's application page and submit there. Mark it as applied once sent."
      : "Review your tailored materials and apply through the source link, then mark the application as applied.",
  };
}

/** Creates or updates the application record (materials are generated by the agent). */
export async function prepareApplication(
  userId: string,
  job: Job,
  mode: "MANUAL" | "REVIEW_EVERYTHING" | "SMART_APPLY" | "AUTOPILOT" = "REVIEW_EVERYTHING"
): Promise<PrepareApplicationResult> {
  const agent = await ApplicationAgent.processApplication(userId, job, mode);

  const application = (await db.application.findFirst({
    where: { userId, jobId: job.id },
    include: { documents: true, answers: true, events: true },
  })) as (Application & { documents?: { type: string }[]; answers?: unknown[] }) | null;

  if (!application) {
    throw new Error("Application record was not created");
  }

  // Attach the base resume + cover letter document for tracking.
  const defaultResume = await db.resume.findFirst({ where: { userId, isDefault: true } });
  const resume = defaultResume || (await db.resume.findFirst({ where: { userId } }));
  const coverLetterDoc = (application.documents || []).find((doc) => doc.type === "COVER_LETTER") as
    | { id: string }
    | undefined;

  const updated = (await db.application.update({
    where: { id: application.id },
    data: {
      resumeId: resume?.id || null,
      coverLetterId: coverLetterDoc?.id || null,
    },
  })) as Application;

  const readiness = buildReadiness(
    { ...updated, answers: application.answers } as Application,
    job,
    application.documents || []
  );

  return {
    application: { ...updated, documents: application.documents, answers: application.answers, events: application.events } as Application,
    readiness,
    agent,
    job: toPublicJob(job),
    message: readiness.ready
      ? `${sourceLabelForProvider(job.provider, job.source)} role at ${job.company}: materials are ready. Apply on the employer's site to complete your application.`
      : "Materials are being prepared - some items are still missing.",
  };
}

/** Records a swipe decision, preventing duplicate swipe rows. */
export async function recordSwipe(
  userId: string,
  job: Job,
  action: SwipeAction
): Promise<{ interaction: JobInteraction; created: boolean; job: Job }> {
  if (job.canonicalJobId) {
    throw Object.assign(new Error("This opening is a duplicate of another listing"), { statusCode: 409 });
  }
  if (!job.isActive) {
    throw Object.assign(new Error("This job is no longer accepting new swipes"), { statusCode: 409 });
  }

  const interactionType = SWIPE_TO_INTERACTION[action];
  const existing = (await db.jobInteraction.findMany({ where: { userId, jobId: job.id } })) as JobInteraction[];

  const sameAction = existing.find((entry) => entry.interactionType === interactionType);
  if (sameAction) {
    return { interaction: sameAction, created: false, job };
  }

  // One swipe decision per user/job: replace any previous swipe.
  for (const entry of existing) {
    if (entry.interactionType === "LIKE" || entry.interactionType === "SUPER_LIKE" || entry.interactionType === "PASSED") {
      await db.jobInteraction.delete({ where: { id: entry.id } });
    }
  }

  const interaction = (await db.jobInteraction.create({
    data: {
      userId,
      jobId: job.id,
      interactionType,
      metadata: { action, swipedAt: new Date().toISOString(), matchScore: job.matchScore ?? null },
    },
  })) as JobInteraction;

  return { interaction, created: true, job };
}

/** Marks an application as applied after the user confirms they submitted it. */
export async function markAppliedExternally(userId: string, applicationId: string): Promise<Application> {
  const application = (await db.application.findUnique({ where: { id: applicationId } })) as Application | null;
  if (!application || application.userId !== userId) {
    throw Object.assign(new Error("Application not found"), { statusCode: 404 });
  }

  const timestamp = new Date().toISOString();
  const updated = (await db.application.update({
    where: { id: applicationId },
    data: {
      status: "APPLIED",
      appliedAt: application.appliedAt || timestamp,
      submittedAt: application.submittedAt || timestamp,
      submissionMethod: "USER_CONFIRMED_EXTERNAL",
    },
  })) as Application;

  await db.applicationEvent.create({
    data: {
      applicationId,
      eventType: "APPLIED",
      notes: "Candidate confirmed the application was submitted on the employer's site.",
    },
  });

  await db.notification.create({
    data: {
      userId,
      title: "Application marked as applied ✅",
      message: "We logged your application and will surface similar roles that fit your profile.",
      type: "APPLICATION_SUBMITTED",
      link: `/dashboard/applications/${applicationId}`,
    },
  });

  return updated;
}

export async function getApplicationForUser(
  userId: string,
  applicationId: string
): Promise<(Application & { job?: Job | null }) | null> {
  const application = (await db.application.findUnique({
    where: { id: applicationId },
    include: { job: true, answers: true, documents: true, events: true },
  })) as (Application & { job?: Job | null }) | null;

  if (!application || application.userId !== userId) return null;
  return application;
}

export async function listUserApplications(userId: string, status?: string) {
  const where: Record<string, unknown> = { userId };
  if (status) where.status = status;

  return (await db.application.findMany({
    where,
    include: { job: true, answers: true, documents: true, events: true },
    orderBy: { updatedAt: "desc" },
  })) as Application[];
}

/** Saves or unsaves a job for a user (idempotent). */
export async function toggleSavedJob(
  userId: string,
  job: Job
): Promise<{ isSaved: boolean }> {
  const existing = await db.savedJob.findFirst({ where: { userId, jobId: job.id } });

  if (existing) {
    await db.savedJob.delete({ where: { id: existing.id } });
    return { isSaved: false };
  }

  await db.savedJob.create({ data: { userId, jobId: job.id } });

  const savedInteraction = await db.jobInteraction.findFirst({
    where: { userId, jobId: job.id, interactionType: "SAVED" },
  });
  if (!savedInteraction) {
    await db.jobInteraction.create({
      data: { userId, jobId: job.id, interactionType: "SAVED" },
    });
  }

  return { isSaved: true };
}

/** Best-effort audit trail for the admin sync log. */
export async function logApplicationEvent(applicationId: string, eventType: string, notes?: string) {
  try {
    await db.applicationEvent.create({ data: { applicationId, eventType, notes: notes || null } });
  } catch (error) {
    log.warn("failed to log application event", { applicationId, eventType, error: (error as Error).message });
  }
}
